package practice.oop.task8.models;

public enum PlayerRace {
AARAKOCRA, AASIMAR, AUTOGNOME, BUGBEAR, CENTAUR, CHANGELING, DHAMPIR, DRAGONBORN, DWARF, ELF, ASTRAL_ELF, ELADRIN, SEA_ELF, SHADAR_KAI, FAIRY, FIRBOLG, GENASI, AIR_GENASI, EARTH_GENASI, FIRE_GENASI, WATER_GENASI, GIFF, GITH, GITHYANKI, GITHZERAI, GNOME, DEEP_GNOME, GOBLIN, GOLIATH, HADOZEE, HALF_ELF, HALF_ORC, HALFLING, HARENGON, HEXBLOOD, HOBGOBLIN, HUMAN, KALASHTAR, KENDER, KENKU, KOBOLD, LEONIN, LIZARDFOLK, LOXODON, MINOTAUR, ORC, OWLIN, PLASMOID, REBORN, SATYR, SHIFTER, SIMIC_HYBRID, TABAXI, THRI_KREEN, TIEFLING, TORTLE, TRITON, VEDALKEN, VERDAN, WARFORGED, YUAN_TI;
}
