package practice.oop.task8.models;

public enum PlayerType {
    
    ARCHON, ASSASSIN, BARD, BEASTMASTER, BLADEDANCER, CABALIST, CHAMPION, CHLOROMANCER, DOMINATOR, DRUID, ELEMENTALIST, INQUISITOR, JUSTICIAR, LIBERATOR, MARKSMAN, NECROMANCER, NIGHTBLADE, PALADIN, PARAGON, PURIFIER, PYROMANCER, RANGER, REAVER, RIFTBLADE, RIFTSTALKER, SABOTEUR, SENTINEL, SHAMAN, STORMCALLER, TEMPEST, VOID_KNIGHT, WARDEN, WARLOCK, WARLORD;
}
